### ISSUE TITLE
Default values for fields

### ISSUE THREAD

**Issue by Suncatcher** [mitchcapper/KPEntryTemplates#13]
Hi,
the plugin is very cool but I cannot sort out how to assign default values for template fields. 
I can create entries from templates but these entries are always empty (except listboxes). How to populate them with necessary data? Maybe I am missing something?

**Comment by mitchcapper** [comment]
technically this creates a UI for it not set defaults. Defaults you would set on the template field itself (and then make sure when creating a new entry to select the template there (as using set template parent will not import the defaults otherwise).

**Comment by Suncatcher** [comment]
> Defaults you would set on the template field itself
How? What is *template field itself*?
This is what I see inside template

![image](https://cloud.githubusercontent.com/assets/6388034/22466204/ee34c3a4-e7c7-11e6-8d01-6a564abaa90c.png)


![image](https://cloud.githubusercontent.com/assets/6388034/22466190/d8a2ded6-e7c7-11e6-9260-0a0b892a8845.png)

Where should I put the defaults? Into *_etm_options_* string fields? I tried but it had no effect.

And that's what I see when I create new entry from template
I select template from the dropdown menu like this

![screenshot 2017-01-31 15 15 41](https://cloud.githubusercontent.com/assets/6388034/22466287/505ddade-e7c8-11e6-8422-3dbd596b4fa1.png)

And the fields of template are always empty!!!

![image](https://cloud.githubusercontent.com/assets/6388034/22466326/7000d15c-e7c8-11e6-9885-df492550c85d.png)

What am I doing wrong?

**Comment by mitchcapper** [comment]
Do not edit the _etm entries, that would be potentially bad.  Instead say you want a default for your "Card holder" field.  Now you assigned that field name "Card holder".  Create a string in advanced called "Card holder" and put in it whatever you want the default value you be, that is how the native templates with keepass works.  If you can write up a short blurb as a PR on the readme that would be great for others who might also have said confusion.

**Comment by Suncatcher** [comment]
Excellent! It works.

> If you can write up a short blurb as a PR on the readme that would be great for others who might also have said confusion.

Well, I'll try.

**Comment by YoNevelt** [comment]
I'm facing the same issue but the mentioned method doesn't appear to work.
1) create new template / edit one
2) add desired fields
3) create a string field in Advanced page named as a field in the Template and the value which supposed to be the default value for that field
4) create entry
5) set as a template child entry 

Now, I can see the extra advanced fields I added but the one with default value does not have any value still.
What's the workaround it? Is there any policy I need to check?

**Comment by mitchcapper** [comment]
@YoNevelt that is because you are using "Set Template Parent" after the entry is created.   What this does is simply create the _etm entry to associate it with the parent and shows the UI.

To get default values you are essentially relying on the keepass built in templating support.  This means rather than your normal "create entry/add entry" you want to use the template creation dropdown.

In the toolbar click the down arrow next to the add entry key icon and select the template you want:
![image](https://github.com/user-attachments/assets/9ed3cbf2-a2eb-49ca-b390-b357573f14ce)

This will do two things:
*) Set the template parent automatically to that template
*) Copy all the default values from that template to the new entry (what you are asking about)

**Comment by YoNevelt** [comment]
Thank you! This was the solution.
