### ISSUE TITLE
Overlapped Notes Field in Entry tab

### ISSUE THREAD

**Issue by iamhammer** [mitchcapper/KPEntryTemplates#31]
On Template files and entries created from a Template, the Expiry fields at the bottom of the Entry tab are overlapped by the Notes field.
 
Here is a regular entry:
![image](https://user-images.githubusercontent.com/1703116/35590956-5dcc8bb6-05d6-11e8-8a11-e029283ca1bb.png)

Here is an entry created from a template:
![image](https://user-images.githubusercontent.com/1703116/35591049-a70fcdba-05d6-11e8-90ae-4ce473984810.png)

**Comment by ltdeta** [comment]
same problem!

**Comment by mitchcapper** [comment]
I am guessing this is related to the scaling causing an issue.  Does this happen with 2.39? I am guessing it doesn't happen on the template tab only on the main one.  Does it always happen?  What resolution and zoom are you using?

**Comment by iamhammer** [comment]
Cannot test on 2.39. The plugin is not compatible with that version of KeePass.

**Comment by mitchcapper** [comment]
@iamhammer  see #39 for a 2.39 preview.

**Comment by iamhammer** [comment]
Just tested. No change.

**Comment by iamhammer** [comment]
Just tested. No change.
To answer your previous questions:

- This does happen in 2.39 with your preview from PR #39 .
- This specific field is only present and effected on the Entry tab. The Template tab has some other height and width issues I will submit as a separate issue.
- It does always happen, whether editing the parent template, or a child entry based on the template.
- I run KeePass portable on a few different systems, each having multiple monitors and running different resolutions on each monitor. The display is consistent and does not appear to be tied to resolution or scaling settings.

**Comment by ayyubmd** [comment]
Even I faced this issue, this happens when my system display setting are in 150% scale and keepass application compatibility setting set to -> **High DPI Scaling Override is set to "Application".**  
<img width="253" alt="high dpi setting" src="https://user-images.githubusercontent.com/22093628/46455821-50ef9580-c7ca-11e8-9eeb-24d05c83ad2f.PNG">
![dpi 02](https://user-images.githubusercontent.com/22093628/46455822-51882c00-c7ca-11e8-9bda-295683efbbe8.png)
When I have keepass set compatibility setting to -> **High DPI Scaling override to "System (Enhanced)"** it was working fine **but the Keepass window looks blur.**

![dpi 01](https://user-images.githubusercontent.com/22093628/46455945-bb083a80-c7ca-11e8-86f2-3627871a4bcc.png)

Below are my display setting

<img width="960" alt="display settings" src="https://user-images.githubusercontent.com/22093628/46455989-db37f980-c7ca-11e8-841d-f6e24bf4f4e3.PNG">

**Comment by mitchcapper** [comment]
This should be resolved with the new dpi scaling it no longer is calling the rescale function that lead to this issue.
