### ISSUE TITLE
Width of the field

### ISSUE THREAD

**Issue by Cd-spb** [mitchcapper/KPEntryTemplates#4]
Hello, Mitch Capper!
Sorry my English.

KPEntryTemplates with width of the field.
KeePass 2.31 on Windows 7x64:
<img width="368" alt="entry_kpentrytemplates-6 01" src="https://cloud.githubusercontent.com/assets/16777297/12418490/b0c52c92-bec0-11e5-8759-bb08e5269ad6.png">
kpentrytemplates-6.01 - Ok
English

---

<img width="368" alt="entry_kpentrytemplates-6 01_ru" src="https://cloud.githubusercontent.com/assets/16777297/12418493/b0d92ae4-bec0-11e5-9320-e8c0e3c12e5c.png">
kpentrytemplates-6.01 - Ok
Russian

---

<img width="368" alt="entry_kpentrytemplates-7 0 0 1" src="https://cloud.githubusercontent.com/assets/16777297/12418495/b0dd7c5c-bec0-11e5-9189-aa46ae564775.png">
kpentrytemplates-7.0.0.1 - BAD!
English

---

<img width="368" alt="entry_kpentrytemplates-7 0 0 1_ru" src="https://cloud.githubusercontent.com/assets/16777297/12418491/b0d70818-bec0-11e5-89da-3e3171df3dd4.png">
kpentrytemplates-7.0.0.1 - very BAD!
Russian

**Comment by mitchcapper** [comment]
Thanks for finding this,  I am working to see how we can fix it.

**Comment by mitchcapper** [comment]
This is due to the DPI scaling and an unknown issue when we scale the form using the suggested methods.  We are working to manually scale the fields which should fix it,  If you are not on a high DPI machine or don't mind very small fields for now you can comment out:
https://github.com/mitchcapper/KPEntryTemplates/blob/master/EntryTemplateManager.ChildViewer.cs#L40,L41
which will prevent the form from being sized incorrectly.

**Comment by mitchcapper** [comment]
this was resolved in the previous scaling commit.

**Comment by Cd-spb** [comment]
Thanx!
